#+title: vagrant-archlinux-sample
#+author: conao3

[[https://github.com/conao3/vagrant-archlinux-sample/blob/master/LICENSE][https://img.shields.io/github/license/conao3/vagrant-archlinux-sample.svg?style=flat-square]]
[[https://github.com/conao3/vagrant-archlinux-sample/releases][https://img.shields.io/github/tag/conao3/vagrant-archlinux-sample.svg?style=flat-square]]

* Overview

A ready-to-use Vagrant configuration for spinning up Arch Linux virtual machines. This project uses [[https://github.com/elasticdog/packer-arch][packer-arch]] to build custom Arch Linux boxes.

* Prerequisites

| Tool       | Version  | Description                        |
|------------+----------+------------------------------------|
| VirtualBox | 6.1+     | Virtualization platform            |
| Vagrant    | 2.2+     | Development environment management |
| Packer     | 1.6+     | Machine image builder              |

** Installing on Arch Linux

#+begin_src sh
yay -S linux-headers virtualbox-host-dkms virtualbox vagrant packer
#+end_src

* Getting Started

** Building the Box

First, build the Arch Linux box using Packer:

#+begin_src sh
cd packer-arch
packer build -only=virtualbox-iso arch-template.json
#+end_src

** Adding the Box to Vagrant

Register the built box with Vagrant:

#+begin_src sh
OUTPUT_VERSION=2021.02.01
VERSION=20210201
vagrant box add archlinux-$VERSION output/packer_arch_virtualbox-$OUTPUT_VERSION.box
#+end_src

** Starting the VM

#+begin_src sh
vagrant up
#+end_src

** Connecting via SSH

Once the VM is running, you can connect to it:

#+begin_src sh
vagrant ssh
#+end_src

Or add it to your SSH config for direct access:

#+begin_src sh
vagrant ssh-config >> ~/.ssh/config
ssh default
#+end_src

* Contributing

Contributions are welcome. Feel free to open an issue or submit a pull request.

* License

MIT License. See [[file:LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
